const multer = require("multer");
const uidSafe = require("uid-safe");
const path = require("path");

const aws = require("aws-sdk");
require("dotenv").config();

// * * * * * * * m u l t e r * * * * * * *

//Multer adds body object and a file object to request object.
//body object contains the values of the text fields of the form, the file or files object contains the files uploaded via the form.
//specifies functions that multer should use 
//for determining the path and filename to use when saving files
const storage = multer.diskStorage({
    //destination function tells multer to 
    //put files in the uploads directory 
    //within the parent directory of the file where this code will run
    // destination: function (req, file, callback) {
    //     callback(null, path.join(__dirname, "uploads"));
    // },
    destination: path.join(__dirname, "uploads"),
    //filename function tells multer to use as the file name the unique id generated by the call to uidSafe with the extension of the original file name appended to it. 
    filename: function (req, file, callback) {
        uidSafe(24).then( uid => {
            callback(null, uid + path.extname(file.originalname));
        });
    },
});

//storage object passed to multer 
//along with an object specifying a file size limit
module.exports.uploader = multer({
    storage,
    limits: {
        fileSize: 2097152, //2MB
    },
});


//object returned from this call to multer(uploader) has middleware functions attached to it 
//that can be used to handle uploads on specific routes. 

// * * * * * * * * * * * A W S * * * * * * * * * * *

module.exports.s3 = new aws.S3({
    accessKeyId: process.env.AWS_KEY,
    secretAccessKey: process.env.AWS_SECRET,
});
